import numpy as np
import openmdao.api as om

def get_variable_value(output_file, variable_name, units=None):
    """
    Retrieves the value of a variable from an output file generated by openMDAO with the methods list_outputs(hierarchical=FALSE).

    Parameters:
        output_file (str): The path to the output file.
        variable_name (str): The name of the variable to retrieve.
        units (str, optional): The desired units for the variable value. Defaults to None.

    Returns:
        float: The value of the variable.

    Raises:
        ValueError: If the variable is not found in the file.
    """
    with open(output_file) as file:
        lines = file.readlines()
    for line in lines:
        if variable_name in line:
            # Remove brackets and convert to float
            columns = line.split()
            if units is not None:
                value = columns[1].replace('[', '').replace(']', '')
                value = float(value)
                if columns[2] != units:
                    value = om.convert_units(value, columns[2], units)
                return value
            value = line.split()[1].replace('[', '').replace(']', '')
            return float(value)

    raise ValueError(f'Variable {variable_name} not found in file')